languageCode: "en-us"
title: "tweakflow - safe embeddable scripting language for the JVM"
theme: "hugo-tweakflow"
uglyurls: true
relativeURLs: true
menu:

  mainleft:
    - Name: "Getting started"
      URL: "/getting-started.html"
      Weight: -500

    - Name: "Tools"
      URL: "/tools.html"
      Weight: -400

    - Name: "Embedding"
      URL: "/embedding.html"
      Weight: -200

    - Name: "Reference"
      URL: "/reference.html"
      Weight: -100

    - Name: "Support"
      URL: "/support.html"
      Weight: 0

  mainright:

    - Name: "std"
      URL: "/modules/std.html"
      Weight: -300

    - Name: "std/spec"
      URL: "/modules/std/spec.html"
      Weight: -250

    - Name: "GitHub"
      URL: "https://github.com/twineworks/tweakflow/"
      Weight: -200

    - Name: "Discuss"
      URL: "https://gitter.im/twineworks/tweakflow"
      Weight: -100



params:
  # shortcode {{< gitRef >}}
  gitRef: "master"
  # shortcode {{< version >}}
  version: "0.15.0"
